name: "Lint"
on: [push, pull_request]
jobs:
  lint:
    name: Run YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
